---
title: "for chat"
author: "Justin Herman"
date: "April 11, 2018"
output: html_document
---

## load Libraries
```{r message=FALSE}
library(ggplot2)
library(lubridate)
library(Scale)
library(reshape2)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(stringr)
library(syuzhet) 
library(dplyr ) 
library(tidyverse)
library(rlang)
library(scales)
library(RColorBrewer )
library(ggthemes)
library(tidytext)
library(knitr)
```



```{r}
    my_data <- read.csv("new_whats_app.csv",stringsAsFactors =FALSE)
as.data.frame(my_data)


colourCount = length(unique(my_data$name))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))


my_data$time <- as.POSIXlt(my_data$time)

```

## 12-4PM
```{r}
ggplot(my_data[my_data$time$hour >=12 &my_data$time$hour <16,], aes(x = time$hour, fill = name)) +
  stat_count(position = "dodge", show.legend = TRUE) +
  ggtitle("12-4PM conversations per hour") +
  ylab("# of messages") + xlab("time") +
  theme(plot.title = element_text(face = "italic"))
```

## 4-8 PM
```{r}
ggplot(my_data[my_data$time$hour >16 &my_data$time$hour <=20,], aes(x = time$hour, fill = name)) +
  stat_count(position = "dodge", show.legend = TRUE) +
  ggtitle("12-4PM conversations per hour") +
  ylab("# of messages") + xlab("time") +
  theme(plot.title = element_text(face = "italic"))
```

## 8-12PM

```{r}
ggplot(my_data[my_data$time$hour >20 &my_data$time$hour <=24,], aes(x = time$hour, fill = name)) +
  stat_count(position = "dodge", show.legend = TRUE) +
  ggtitle("12-4PM conversations per hour") +
  ylab("# of messages") + xlab("time") +
  theme(plot.title = element_text(face = "italic"))
```

